export const providers = {
  gemini: {
    name: 'Gemini',
    model: 'gemini-2.5-flash',
    url: 'https://gemini.google.com/app',
    loginUrl: 'https://accounts.google.com/',
    input: ['div.ql-editor.textarea[contenteditable="true"]', 'div.ql-editor[contenteditable="true"]', '[aria-label="Enter a prompt for Gemini"]', '[role="textbox"][contenteditable="true"]', 'rich-textarea [contenteditable="true"]', 'textarea[placeholder="Ask Gemini"]', 'textarea'],
    send: ['button[aria-label="Send message"]', 'button[aria-label*="Send message"]', 'button[aria-label*="Send"]', 'button.send-button', 'button[data-test-id="send-button"]'],
    response: ['model-response message-content', 'model-response', 'message-content .markdown', 'message-content', '.model-response-text', '[data-test-id="response-content"]', '.response-content', '[class*="model-response"]', '.markdown.markdown-main-panel'],
  },
  deepseek: {
    name: 'DeepSeek',
    model: 'deepseek-chat',
    url: 'https://chat.deepseek.com/',
    loginUrl: 'https://chat.deepseek.com/sign_in',
    email: ['input[type="email"]', 'input[name="email"]', 'input[placeholder*="mail" i]', 'input[placeholder*="phone" i]', 'input'],
    password: ['input[type="password"]', 'input[name="password"]'],
    loginSubmit: ['button[type="submit"]', 'button:has-text("Log in")', 'button:has-text("Sign in")', 'button:has-text("Continue")'],
    input: ['textarea#chat-input', 'textarea'],
    send: ['button[aria-label*="Send"]', 'button[type="submit"]'],
    response: ['.ds-markdown', '[class*="markdown"]'],
  },
  claude: {
    name: 'Claude',
    model: 'claude-sonnet',
    url: 'https://claude.ai/new',
    loginUrl: 'https://claude.ai/login',
    email: ['input[type="email"]', 'input[name="email"]'],
    password: ['input[type="password"]'],
    loginSubmit: ['button[type="submit"]', 'button:has-text("Continue")'],
    input: ['div[contenteditable="true"]', 'textarea'],
    send: ['button[aria-label*="Send"]', 'button[type="submit"]'],
    response: ['[data-is-streaming="false"] .font-claude-response', '[data-testid="assistant-message"]'],
  },
  chatgpt: {
    name: 'ChatGPT',
    model: 'auto',
    url: 'https://chatgpt.com/',
    loginUrl: 'https://chatgpt.com/auth/login',
    email: ['input[type="email"]', '#username', 'input[name="username"]'],
    password: ['input[type="password"]', '#password'],
    loginSubmit: ['button[type="submit"]', 'button:has-text("Continue")'],
    input: ['#prompt-textarea', 'textarea'],
    send: ['button[data-testid="send-button"]', 'button[aria-label*="Send"]'],
    response: ['[data-message-author-role="assistant"]'],
  },
};
